### ISSUE TITLE
请问一下

### ISSUE THREAD

**Issue by hhb19900618** [iphone5solo/PYPhotosView#2]
你不是使用 MPMoviePlayerController 作为播放器吗？
为什么本地还需开启 HTTPServer？

**Comment by iphone5solo** [comment]
为了做视频边播放边缓存，实现原理是：在本地开启一个本地服务器，本地不断发生下载请求到资源服务器，MPMoviePlayerController不断地向本地发送请求。 本地服务器就相当于一个代理。

**Comment by hhb19900618** [comment]
不开启HTTPServer  也能播放本地视频吧

**Comment by iphone5solo** [comment]
是能播放，但如果是网络视频，就需要弄HTTPServer 才能做到边播放边下载， 或者你可以用AVPlayer播放器，它好像也有类似于代理这个东西来做边播放边下载，具体我还没去研究,你可以去研究下。

**Comment by hhb19900618** [comment]
ASIHTTPRequest 支持ipv6吗

**Comment by iphone5solo** [comment]
我在知乎上看到的：“支持，它是基于CFNetwork的，苹果有说明CFNetwork库是支持IPV6的” ，但这种框架最好慎用 因为它已经停止更新了。 如果你不自己维护这个框架，最好不要用。我当时用只是测试和了解一下那个边播放边缓存的原理，等不忙的时候，会自己写一个的。
