### ISSUE TITLE
点击以发布图片的问题

### ISSUE THREAD

**Issue by yujia917** [iphone5solo/PYPhotosView#4]
加载完已发布网络图片后，点击图片的时候不管点击的是第几张，弹出的总是第一张， 但是下面的page index显示是正确的。点击本地图片的时候就没有这个问题。 这个怎么解决？ 当再次点击预览图片缩小的时候，就有以下的信息

Could not load the "close" image referenced from a nib in the bundle with identifier "xxxx"
Could not load the "more " image referenced from a nib in the bundle with identifier "xxxx"
 Could not load the "play_1" image referenced from a nib in the bundle with identifier "xxxx"
 Could not load the "pause" image referenced from a nib in the bundle with identifier "xxxx"
 Could not load the "play" image referenced from a nib in the bundle with identifier "xxxx"
 Could not load the "close" image referenced from a nib in the bundle with identifier "xxxx"
 Could not load the "more " image referenced from a nib in the bundle with identifier "xxxx"
Could not load the "play_1" image referenced from a nib in the bundle with identifier "xxxx"
 Could not load the "pause" image referenced from a nib in the bundle with identifier "xxxx"
 Could not load the "play" image referenced from a nib in the bundle with identifier "xxxx"

**Comment by iphone5solo** [comment]
谢谢您的反馈，这个BUG是出现在iOS8系统下，现在已经修复，请下载最新版测试！

**Comment by yujia917** [comment]
多谢！
